language: node_js
node_js:
  - stable
cache:
  yarn: true

script: yarn test

before_deploy:
  - export PATH=$PATH:`yarn global bin` # temporary until TravisCI fixes issue
  - yarn build
  - yarn global add serverless
deploy:
  provider: script
  script: serverless deploy --stage production
  skip_cleanup: true
  on:
    branch: master
