language: node_js
node_js:
  - stable
cache:
  yarn: true

script: yarn test

before_deploy:
  - yarn global add serverless
  - yarn build
deploy:
  provider: script
  script: serverless deploy --stage production
  skip_cleanup: true
  on:
    branch: master
