language: node_js
node_js:
  - stable
cache:
  yarn: true

before_install:
  - export PATH=$PATH:`yarn global bin` # temporary until TravisCI fixes issue
  - yarn global add serverless
install: yarn

script: yarn test

before_deploy: yarn build
deploy:
  provider: script
  script: serverless deploy --stage production
  skip_cleanup: true
  on:
    branch: master
