service: email-handler

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

package:
  include:
    - handler.js
    - util/**
    - config/**

functions:
  send:
    handler: handler.email
    events:
      - http:
          path: email
          method: post
          cors: true
