service: email-handler

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline
  - serverless-plugin-warmup

functions:
  send:
    handler: dist/handler.email
    warmup: true
    events:
      - http:
          path: email
          method: post
          cors: true

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"
